#pragma once

// Generated by tools/pack_icon_atlas.py - do not edit by hand.
// All scale-specific atlases share this fixed-grid UV layout.

enum class UiIconId
{
    Resume,
    Reset,
    Save,
    Load,
    SaveSlot,
    RomList,
    ResetView,
    Settings,
    Move,
    Back,
    Exit,
    FollowHead,
    Distance,
    Scale,
    LeftRight,
    UpDown,
    Ipd,
    ButtonA,
    ButtonB,
    ButtonX,
    ButtonY,
    TwoD,
    ThreeD,
    ForceDmg,
    Mapping,
    Palette,
    Header,
    VbCartridge,
    MapLeftUp,
    MapLeftDown,
    MapLeftLeft,
    MapLeftRight,
    MapRightUp,
    MapRightDown,
    MapRightLeft,
    MapRightRight,
    MapStart,
    MapSelect,
    MapTriggerLeft,
    MapTriggerRight,
    Count,
    None = Count,
};

struct UiIconUv
{
    float u0, v0, u1, v1;
    int width, height;
};

inline constexpr int kIconAtlasWidth = 96;
inline constexpr int kIconAtlasHeight = 60;

inline constexpr UiIconUv kIconUvs[static_cast<size_t>(UiIconId::Count)] = {
    { 0.010417f, 0.016667f, 0.114583f, 0.183333f, 10, 10 }, // Resume
    { 0.135417f, 0.016667f, 0.239583f, 0.183333f, 10, 10 }, // Reset
    { 0.260417f, 0.016667f, 0.364583f, 0.183333f, 10, 10 }, // Save
    { 0.385417f, 0.016667f, 0.489583f, 0.183333f, 10, 10 }, // Load
    { 0.510417f, 0.016667f, 0.614583f, 0.183333f, 10, 10 }, // SaveSlot
    { 0.635417f, 0.016667f, 0.739583f, 0.183333f, 10, 10 }, // RomList
    { 0.760417f, 0.016667f, 0.864583f, 0.183333f, 10, 10 }, // ResetView
    { 0.885417f, 0.016667f, 0.989583f, 0.183333f, 10, 10 }, // Settings
    { 0.010417f, 0.216667f, 0.114583f, 0.383333f, 10, 10 }, // Move
    { 0.135417f, 0.216667f, 0.239583f, 0.383333f, 10, 10 }, // Back
    { 0.260417f, 0.216667f, 0.364583f, 0.383333f, 10, 10 }, // Exit
    { 0.385417f, 0.216667f, 0.489583f, 0.383333f, 10, 10 }, // FollowHead
    { 0.510417f, 0.216667f, 0.614583f, 0.383333f, 10, 10 }, // Distance
    { 0.635417f, 0.216667f, 0.739583f, 0.383333f, 10, 10 }, // Scale
    { 0.760417f, 0.216667f, 0.864583f, 0.383333f, 10, 10 }, // LeftRight
    { 0.885417f, 0.216667f, 0.989583f, 0.383333f, 10, 10 }, // UpDown
    { 0.010417f, 0.416667f, 0.114583f, 0.583333f, 10, 10 }, // Ipd
    { 0.135417f, 0.416667f, 0.239583f, 0.583333f, 10, 10 }, // ButtonA
    { 0.260417f, 0.416667f, 0.364583f, 0.583333f, 10, 10 }, // ButtonB
    { 0.385417f, 0.416667f, 0.489583f, 0.583333f, 10, 10 }, // ButtonX
    { 0.510417f, 0.416667f, 0.614583f, 0.583333f, 10, 10 }, // ButtonY
    { 0.635417f, 0.416667f, 0.739583f, 0.583333f, 10, 10 }, // TwoD
    { 0.760417f, 0.416667f, 0.864583f, 0.583333f, 10, 10 }, // ThreeD
    { 0.885417f, 0.416667f, 0.989583f, 0.583333f, 10, 10 }, // ForceDmg
    { 0.010417f, 0.616667f, 0.114583f, 0.783333f, 10, 10 }, // Mapping
    { 0.135417f, 0.616667f, 0.239583f, 0.783333f, 10, 10 }, // Palette
    { 0.260417f, 0.616667f, 0.364583f, 0.783333f, 10, 10 }, // Header
    { 0.385417f, 0.616667f, 0.489583f, 0.783333f, 10, 10 }, // VbCartridge
    { 0.510417f, 0.616667f, 0.614583f, 0.783333f, 10, 10 }, // MapLeftUp
    { 0.635417f, 0.616667f, 0.739583f, 0.783333f, 10, 10 }, // MapLeftDown
    { 0.760417f, 0.616667f, 0.864583f, 0.783333f, 10, 10 }, // MapLeftLeft
    { 0.885417f, 0.616667f, 0.989583f, 0.783333f, 10, 10 }, // MapLeftRight
    { 0.010417f, 0.816667f, 0.114583f, 0.983333f, 10, 10 }, // MapRightUp
    { 0.135417f, 0.816667f, 0.239583f, 0.983333f, 10, 10 }, // MapRightDown
    { 0.260417f, 0.816667f, 0.364583f, 0.983333f, 10, 10 }, // MapRightLeft
    { 0.385417f, 0.816667f, 0.489583f, 0.983333f, 10, 10 }, // MapRightRight
    { 0.510417f, 0.816667f, 0.614583f, 0.983333f, 10, 10 }, // MapStart
    { 0.635417f, 0.816667f, 0.739583f, 0.983333f, 10, 10 }, // MapSelect
    { 0.760417f, 0.816667f, 0.864583f, 0.983333f, 10, 10 }, // MapTriggerLeft
    { 0.885417f, 0.816667f, 0.989583f, 0.983333f, 10, 10 }, // MapTriggerRight
};
