#pragma once

// Generated by tools/pack_icon_atlas.py - do not edit by hand.
// Re-run the script (see its docstring) after changing the icon set,
// and commit both this header and assets/icons/icons_atlas.png together.

enum class UiIconId
{
    Resume,
    Reset,
    Save,
    Load,
    SaveSlot,
    RomList,
    ResetView,
    Settings,
    Move,
    Back,
    Exit,
    FollowHead,
    Distance,
    Scale,
    LeftRight,
    UpDown,
    Ipd,
    ButtonA,
    ButtonB,
    ButtonX,
    ButtonY,
    TwoD,
    ThreeD,
    ForceDmg,
    Mapping,
    Palette,
    Header,
    MapLeftUp,
    MapLeftDown,
    MapLeftLeft,
    MapLeftRight,
    MapRightUp,
    MapRightDown,
    MapRightLeft,
    MapRightRight,
    MapStart,
    MapSelect,
    MapTriggerLeft,
    MapTriggerRight,
    Count,
    None = Count,
};

struct UiIconUv
{
    float u0, v0, u1, v1;
    int width, height;
};

inline constexpr int kIconAtlasWidth = 256;
inline constexpr int kIconAtlasHeight = 193;

inline constexpr UiIconUv kIconUvs[static_cast<size_t>(UiIconId::Count)] = {
    { 0.300781f, 0.005181f, 0.410156f, 0.150259f, 28, 28 }, // Resume
    { 0.414062f, 0.005181f, 0.523438f, 0.150259f, 28, 28 }, // Reset
    { 0.527344f, 0.005181f, 0.636719f, 0.150259f, 28, 28 }, // Save
    { 0.640625f, 0.005181f, 0.750000f, 0.150259f, 28, 28 }, // Load
    { 0.753906f, 0.005181f, 0.863281f, 0.150259f, 28, 28 }, // SaveSlot
    { 0.867188f, 0.005181f, 0.976562f, 0.150259f, 28, 28 }, // RomList
    { 0.003906f, 0.398964f, 0.113281f, 0.544041f, 28, 28 }, // ResetView
    { 0.117188f, 0.398964f, 0.226562f, 0.544041f, 28, 28 }, // Settings
    { 0.230469f, 0.398964f, 0.339844f, 0.544041f, 28, 28 }, // Move
    { 0.343750f, 0.398964f, 0.453125f, 0.544041f, 28, 28 }, // Back
    { 0.457031f, 0.398964f, 0.566406f, 0.544041f, 28, 28 }, // Exit
    { 0.570312f, 0.398964f, 0.679688f, 0.544041f, 28, 28 }, // FollowHead
    { 0.683594f, 0.398964f, 0.792969f, 0.544041f, 28, 28 }, // Distance
    { 0.796875f, 0.398964f, 0.906250f, 0.544041f, 28, 28 }, // Scale
    { 0.003906f, 0.549223f, 0.113281f, 0.694301f, 28, 28 }, // LeftRight
    { 0.117188f, 0.549223f, 0.226562f, 0.694301f, 28, 28 }, // UpDown
    { 0.230469f, 0.549223f, 0.339844f, 0.694301f, 28, 28 }, // Ipd
    { 0.343750f, 0.549223f, 0.453125f, 0.694301f, 28, 28 }, // ButtonA
    { 0.457031f, 0.549223f, 0.566406f, 0.694301f, 28, 28 }, // ButtonB
    { 0.570312f, 0.549223f, 0.679688f, 0.694301f, 28, 28 }, // ButtonX
    { 0.683594f, 0.549223f, 0.792969f, 0.694301f, 28, 28 }, // ButtonY
    { 0.796875f, 0.549223f, 0.906250f, 0.694301f, 28, 28 }, // TwoD
    { 0.003906f, 0.699482f, 0.113281f, 0.844560f, 28, 28 }, // ThreeD
    { 0.117188f, 0.699482f, 0.226562f, 0.844560f, 28, 28 }, // ForceDmg
    { 0.230469f, 0.699482f, 0.339844f, 0.844560f, 28, 28 }, // Mapping
    { 0.343750f, 0.699482f, 0.453125f, 0.844560f, 28, 28 }, // Palette
    { 0.003906f, 0.005181f, 0.296875f, 0.393782f, 75, 75 }, // Header
    { 0.457031f, 0.699482f, 0.566406f, 0.844560f, 28, 28 }, // MapLeftUp
    { 0.570312f, 0.699482f, 0.679688f, 0.844560f, 28, 28 }, // MapLeftDown
    { 0.683594f, 0.699482f, 0.792969f, 0.844560f, 28, 28 }, // MapLeftLeft
    { 0.796875f, 0.699482f, 0.906250f, 0.844560f, 28, 28 }, // MapLeftRight
    { 0.003906f, 0.849741f, 0.113281f, 0.994819f, 28, 28 }, // MapRightUp
    { 0.117188f, 0.849741f, 0.226562f, 0.994819f, 28, 28 }, // MapRightDown
    { 0.230469f, 0.849741f, 0.339844f, 0.994819f, 28, 28 }, // MapRightLeft
    { 0.343750f, 0.849741f, 0.453125f, 0.994819f, 28, 28 }, // MapRightRight
    { 0.457031f, 0.849741f, 0.566406f, 0.994819f, 28, 28 }, // MapStart
    { 0.570312f, 0.849741f, 0.679688f, 0.994819f, 28, 28 }, // MapSelect
    { 0.683594f, 0.849741f, 0.792969f, 0.994819f, 28, 28 }, // MapTriggerLeft
    { 0.796875f, 0.849741f, 0.906250f, 0.994819f, 28, 28 }, // MapTriggerRight
};
