#!/usr/bin/env python3
"""Packs the old FrontendGo UI icons (uncompressed RGBA .dds files) into a
single PNG atlas, plus a C++ header of UV rects for core/ui/UiIconSet.

Source .dds files live in a sibling checkout (VirtualBoyGoMaster/assets),
not in this repo, so this isn't part of the CMake build - it's a one-off/
rerunnable tool. Re-run it after adding/changing icons and commit the
outputs (assets/icons/icons_atlas.png and core/ui/generated_icons/UiIconAtlas.h).

Usage:
    python tools/pack_icon_atlas.py [path/to/VirtualBoyGoMaster/assets]
"""
import sys
from pathlib import Path

from PIL import Image

# (icon name -> UiIconId, path relative to the assets dir). Order here is
# the enum's declaration order in the generated header.
ICONS = [
    ("Resume", "resume_icon.dds"),
    ("Reset", "reset_icon.dds"),
    ("Save", "save_icon.dds"),
    ("Load", "load_icon.dds"),
    ("SaveSlot", "save_slot_icon.dds"),
    ("RomList", "rom_list_icon.dds"),
    ("ResetView", "reset_view_icon.dds"),
    ("Settings", "settings_icon.dds"),
    ("Move", "move_icon.dds"),
    ("Back", "back_icon.dds"),
    ("Exit", "exit_icon.dds"),
    ("FollowHead", "follow_head_icon.dds"),
    ("Distance", "distance_icon.dds"),
    ("Scale", "scale_icon.dds"),
    ("LeftRight", "leftright_icon.dds"),
    ("UpDown", "updown_icon.dds"),
    ("Ipd", "ipd_icon.dds"),
    ("ButtonA", "button_a_icon.dds"),
    ("ButtonB", "button_b_icon.dds"),
    ("ButtonX", "button_x_icon.dds"),
    ("ButtonY", "button_y_icon.dds"),
    ("TwoD", "2d_icon.dds"),
    ("ThreeD", "3d_icon.dds"),
    ("ForceDmg", "force_dmg_icon.dds"),
    ("Mapping", "mapping_icon.dds"),
    ("Palette", "palette_icon.dds"),
    ("Header", "header_icon.dds"),
    # gb_cartridge.dds/gbc_cartridge.dds/vb_cartridge.dds are excluded: their
    # pixel data decodes as garbled noise regardless of decoder (verified by
    # reinterpreting the raw bytes directly, bypassing Pillow's DDS plugin) -
    # the source files themselves are corrupt. Unused today (ROM list is
    # still a placeholder) - re-add once fixed/re-exported upstream.
    ("MapLeftUp", "icons/mapping/left_up.dds"),
    ("MapLeftDown", "icons/mapping/left_down.dds"),
    ("MapLeftLeft", "icons/mapping/left_left.dds"),
    ("MapLeftRight", "icons/mapping/left_right.dds"),
    ("MapRightUp", "icons/mapping/right_up.dds"),
    ("MapRightDown", "icons/mapping/right_down.dds"),
    ("MapRightLeft", "icons/mapping/right_left.dds"),
    ("MapRightRight", "icons/mapping/right_right.dds"),
    ("MapStart", "icons/mapping/start.dds"),
    ("MapSelect", "icons/mapping/select.dds"),
    ("MapTriggerLeft", "icons/mapping/trigger_left.dds"),
    ("MapTriggerRight", "icons/mapping/trigger_right.dds"),
]

ATLAS_WIDTH = 256
PADDING = 1

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SRC = REPO_ROOT.parent / "VirtualBoyGoMaster" / "assets"
ATLAS_OUT = REPO_ROOT / "assets" / "icons" / "icons_atlas.png"
HEADER_OUT = REPO_ROOT / "core" / "ui" / "generated_icons" / "UiIconAtlas.h"


def shelf_pack(entries):
    """entries: list of (name, PIL.Image). Returns (atlas_size, {name: (x, y)})."""
    # Pack tallest-first into shelves of width ATLAS_WIDTH - simple and
    # plenty good for ~40 small (<=75px) icons.
    ordered = sorted(entries, key=lambda e: e[1].height, reverse=True)

    positions = {}
    x = PADDING
    y = PADDING
    shelf_height = 0
    atlas_width = ATLAS_WIDTH

    for name, img in ordered:
        w, h = img.size
        if x + w + PADDING > atlas_width:
            x = PADDING
            y += shelf_height + PADDING
            shelf_height = 0
        positions[name] = (x, y)
        x += w + PADDING
        shelf_height = max(shelf_height, h)

    atlas_height = y + shelf_height + PADDING
    return atlas_width, atlas_height, positions


def main():
    src_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    if not src_dir.is_dir():
        sys.exit(f"Source assets dir not found: {src_dir}")

    loaded = []
    for name, rel_path in ICONS:
        path = src_dir / rel_path
        img = Image.open(path).convert("RGBA")
        loaded.append((name, img))

    atlas_width, atlas_height, positions = shelf_pack(loaded)

    atlas = Image.new("RGBA", (atlas_width, atlas_height), (0, 0, 0, 0))
    rects_px = {}
    for name, img in loaded:
        x, y = positions[name]
        atlas.paste(img, (x, y))
        rects_px[name] = (x, y, img.width, img.height)

    ATLAS_OUT.parent.mkdir(parents=True, exist_ok=True)
    atlas.save(ATLAS_OUT)

    HEADER_OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("// Generated by tools/pack_icon_atlas.py - do not edit by hand.")
    lines.append("// Re-run the script (see its docstring) after changing the icon set,")
    lines.append("// and commit both this header and assets/icons/icons_atlas.png together.")
    lines.append("")
    lines.append("enum class UiIconId")
    lines.append("{")
    for name, _ in ICONS:
        lines.append(f"    {name},")
    lines.append("    Count,")
    lines.append("    None = Count,")
    lines.append("};")
    lines.append("")
    lines.append("struct UiIconUv")
    lines.append("{")
    lines.append("    float u0, v0, u1, v1;")
    lines.append("    int width, height;")
    lines.append("};")
    lines.append("")
    lines.append(f"inline constexpr int kIconAtlasWidth = {atlas_width};")
    lines.append(f"inline constexpr int kIconAtlasHeight = {atlas_height};")
    lines.append("")
    lines.append("inline constexpr UiIconUv kIconUvs[static_cast<size_t>(UiIconId::Count)] = {")
    for name, _ in ICONS:
        x, y, w, h = rects_px[name]
        u0 = x / atlas_width
        v0 = y / atlas_height
        u1 = (x + w) / atlas_width
        v1 = (y + h) / atlas_height
        lines.append(f"    {{ {u0:.6f}f, {v0:.6f}f, {u1:.6f}f, {v1:.6f}f, {w}, {h} }}, // {name}")
    lines.append("};")
    lines.append("")

    HEADER_OUT.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {ATLAS_OUT} ({atlas_width}x{atlas_height}, {len(loaded)} icons)")
    print(f"Wrote {HEADER_OUT}")


if __name__ == "__main__":
    main()
