#!/usr/bin/env python3
"""Packs the generated SVG icon PNGs into scale-specific UI atlases.

All atlases use the same fixed grid and therefore share one UV table. Re-run
this after exporting assets/icons/icons_10 through icons_60.

Usage:
    python tools/pack_icon_atlas.py
"""
import sys
from pathlib import Path

from PIL import Image

# (icon name -> UiIconId, path relative to the assets dir). Order here is
# the enum's declaration order in the generated header.
ICONS = [
    ("Resume", "resume_icon.dds"),
    ("Reset", "reset_icon.dds"),
    ("Save", "save_icon.dds"),
    ("Load", "load_icon.dds"),
    ("SaveSlot", "save_slot_icon.dds"),
    ("RomList", "rom_list_icon.dds"),
    ("ResetView", "reset_view_icon.dds"),
    ("Settings", "settings_icon.dds"),
    ("Move", "move_icon.dds"),
    ("Back", "back_icon.dds"),
    ("Exit", "exit_icon.dds"),
    ("FollowHead", "follow_head_icon.dds"),
    ("Distance", "distance_icon.dds"),
    ("Scale", "scale_icon.dds"),
    ("LeftRight", "leftright_icon.dds"),
    ("UpDown", "updown_icon.dds"),
    ("Ipd", "ipd_icon.dds"),
    ("ButtonA", "button_a_icon.dds"),
    ("ButtonB", "button_b_icon.dds"),
    ("ButtonX", "button_x_icon.dds"),
    ("ButtonY", "button_y_icon.dds"),
    ("TwoD", "2d_icon.dds"),
    ("ThreeD", "3d_icon.dds"),
    ("ForceDmg", "force_dmg_icon.dds"),
    ("Mapping", "mapping_icon.dds"),
    ("Palette", "palette_icon.dds"),
    ("Header", "header_icon.dds"),
    ("VbCartridge", "vb_cartridge.dds"),
    # gb_cartridge.dds/gbc_cartridge.dds are excluded - unused (this app is
    # VB-only, no other console cartridge is ever shown).
    ("MapLeftUp", "icons/mapping/left_up.dds"),
    ("MapLeftDown", "icons/mapping/left_down.dds"),
    ("MapLeftLeft", "icons/mapping/left_left.dds"),
    ("MapLeftRight", "icons/mapping/left_right.dds"),
    ("MapRightUp", "icons/mapping/right_up.dds"),
    ("MapRightDown", "icons/mapping/right_down.dds"),
    ("MapRightLeft", "icons/mapping/right_left.dds"),
    ("MapRightRight", "icons/mapping/right_right.dds"),
    ("MapStart", "icons/mapping/start.dds"),
    ("MapSelect", "icons/mapping/select.dds"),
    ("MapTriggerLeft", "icons/mapping/trigger_left.dds"),
    ("MapTriggerRight", "icons/mapping/trigger_right.dds"),
]

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SRC = REPO_ROOT / "assets" / "icons"
ATLAS_SIZES = (10, 20, 30, 40, 50, 60)
ATLAS_COLUMNS = 8
HEADER_OUT = REPO_ROOT / "core" / "ui" / "generated_icons" / "UiIconAtlas.h"


def main():
    src_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    if not src_dir.is_dir():
        sys.exit(f"Source assets dir not found: {src_dir}")

    rows = (len(ICONS) + ATLAS_COLUMNS - 1) // ATLAS_COLUMNS
    rects_px = {}
    base_dimensions = {}
    atlas_width = atlas_height = 0
    for size in ATLAS_SIZES:
        padding = size // 10
        cell = size + padding * 2
        atlas_width = ATLAS_COLUMNS * cell
        atlas_height = rows * cell
        atlas = Image.new("RGBA", (atlas_width, atlas_height), (0, 0, 0, 0))
        for index, (name, rel_path) in enumerate(ICONS):
            png_path = Path(rel_path).with_suffix(".png")
            path = src_dir / f"icons_{size}" / png_path
            img = Image.open(path).convert("RGBA")
            if size == ATLAS_SIZES[0]:
                base_dimensions[name] = img.size
            expected = tuple(d * size // ATLAS_SIZES[0] for d in base_dimensions[name])
            if img.size != expected:
                sys.exit(f"Expected proportional size {expected}, got {img.size}: {path}")
            if img.width > size or img.height > size:
                sys.exit(f"Icon exceeds its {size}px cell: {path}")
            x = (index % ATLAS_COLUMNS) * cell + padding + (size - img.width) // 2
            y = (index // ATLAS_COLUMNS) * cell + padding + (size - img.height) // 2
            atlas.alpha_composite(img, (x, y))
            if size == ATLAS_SIZES[0]:
                rects_px[name] = (x, y, img.width, img.height)

        atlas_out = src_dir / f"icons_atlas_{size}.png"
        atlas.save(atlas_out)
        print(f"Wrote {atlas_out} ({atlas_width}x{atlas_height}, {len(ICONS)} icons)")

    HEADER_OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("// Generated by tools/pack_icon_atlas.py - do not edit by hand.")
    lines.append("// All scale-specific atlases share this fixed-grid UV layout.")
    lines.append("")
    lines.append("enum class UiIconId")
    lines.append("{")
    for name, _ in ICONS:
        lines.append(f"    {name},")
    lines.append("    Count,")
    lines.append("    None = Count,")
    lines.append("};")
    lines.append("")
    lines.append("struct UiIconUv")
    lines.append("{")
    lines.append("    float u0, v0, u1, v1;")
    lines.append("    int width, height;")
    lines.append("};")
    lines.append("")
    base_padding = ATLAS_SIZES[0] // 10
    base_cell = ATLAS_SIZES[0] + base_padding * 2
    base_width = ATLAS_COLUMNS * base_cell
    base_height = rows * base_cell
    lines.append(f"inline constexpr int kIconAtlasWidth = {base_width};")
    lines.append(f"inline constexpr int kIconAtlasHeight = {base_height};")
    lines.append("")
    lines.append("inline constexpr UiIconUv kIconUvs[static_cast<size_t>(UiIconId::Count)] = {")
    for name, _ in ICONS:
        x, y, w, h = rects_px[name]
        u0 = x / base_width
        v0 = y / base_height
        u1 = (x + w) / base_width
        v1 = (y + h) / base_height
        lines.append(f"    {{ {u0:.6f}f, {v0:.6f}f, {u1:.6f}f, {v1:.6f}f, {w}, {h} }}, // {name}")
    lines.append("};")
    lines.append("")

    HEADER_OUT.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {HEADER_OUT}")


if __name__ == "__main__":
    main()
